global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  # — “first.rules”
  # — “second.rules”  \
scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ["Jumping_Jose:8080"]
